package com.bofan.faq.valueobject;

// Generated 2018-2-21 12:16:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.bofan.utils.SchemaConsts;

/**
 * WorkAffixItem generated by hbm2java
 */
@Entity
@Table(name = "FAQ_AFFIX_ITEM", schema = SchemaConsts.EMERGENCY_EVENT_SCHEMA)
@SequenceGenerator(name = "FAQ_AFFIX_ITEM_ID", sequenceName = SchemaConsts.EMERGENCY_EVENT_SCHEMA + ".FAQ_AFFIX_ITEM_ID", allocationSize=1)
public class FaqAffixItem implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
	
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "FAQ_AFFIX_ITEM_ID")
    @Column(name = "FILE_ID", unique = true, nullable = false, precision = 18, scale = 0)
    private Long fileId;

    @Column(name = "SAVE_NAME", nullable = false, length = 500)
    private String saveName;

    @Column(name = "TRUE_NAME", nullable = false, length = 500)
    private String trueName;

    @Column(name = "FILE_SIZE", nullable = false, precision = 18, scale = 0)
    private Long fileSize;

    @Column(name = "IS_IMAGE", nullable = false, length = 1)
    private String isImage;

    @Column(name = "SAVE_PATH", nullable = false, length = 500)
    private String savePath;

    @Column(name = "AFFIX_ID", length = 20)
    private String affixId;
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "AFFIX_ID", nullable = true, insertable = false, updatable = false)
    private FaqAffix affix;

    @Column(name = "PDF_FLAG", length = 1)
    private String pdfFlag;

    public FaqAffixItem() {
    }

    public FaqAffixItem(Long fileId, String saveName, String trueName, Long fileSize, String isImage, String savePath) {
        this.fileId = fileId;
        this.saveName = saveName;
        this.trueName = trueName;
        this.fileSize = fileSize;
        this.isImage = isImage;
        this.savePath = savePath;
    }

    public FaqAffixItem(Long fileId, String saveName, String trueName, Long fileSize, String isImage, String savePath, String affixId, String pdfFlag) {
        this.fileId = fileId;
        this.saveName = saveName;
        this.trueName = trueName;
        this.fileSize = fileSize;
        this.isImage = isImage;
        this.savePath = savePath;
        this.affixId = affixId;
        this.pdfFlag = pdfFlag;
    }

    public Long getFileId() {
        return this.fileId;
    }

    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    public String getSaveName() {
        return this.saveName;
    }

    public void setSaveName(String saveName) {
        this.saveName = saveName;
    }

    public String getTrueName() {
        return this.trueName;
    }

    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }

    public Long getFileSize() {
        return this.fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public String getIsImage() {
        return this.isImage;
    }

    public void setIsImage(String isImage) {
        this.isImage = isImage;
    }

    public String getSavePath() {
        return this.savePath;
    }

    public void setSavePath(String savePath) {
        this.savePath = savePath;
    }

    public String getAffixId() {
        return this.affixId;
    }

    public void setAffixId(String affixId) {
        this.affixId = affixId;
    }

    public String getPdfFlag() {
        return this.pdfFlag;
    }

    public void setPdfFlag(String pdfFlag) {
        this.pdfFlag = pdfFlag;
    }

	public FaqAffix getAffix() {
		return affix;
	}

	public void setAffix(FaqAffix affix) {
		this.affix = affix;
	}

}
